#!/bin/sh

cd include/dvbsi++

echo 'pkgincludedir = ${includedir}/dvbsi++' > Makefile.am
printf "pkginclude_HEADERS =" >> Makefile.am

for file in `ls -1 *.h | sort`; do
	printf ' \\\n\t%s' $file >> Makefile.am
done

echo "" >> Makefile.am

